name: dokit_demo
description: dokit测试工程
version: 0.0.1
homepage: http://flutter.intra.xiaojukeji.com/index.php

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dokit:
    path: ..
  dio: 3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true