name: dokit
description: 开发工具集
version: 0.2.13
homepage: https://www.dokit.cn/#/index/home


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  date_format: ^1.0.8
  vm_service: ^5.5.0
  package_info: ^0.4.3+2
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/dokit_ic_close.png
    - images/dk_frame_hist.png
    - images/dk_method_channel.png
    - images/dk_sys_info.png
    - images/dk_view_check.png
    - images/dk_log_info.png
    - images/dk_ram.png
    - images/dk_view_route.png
    - images/dk_net_monitor.png
    - images/dokit_flutter_btn.png
    - images/dk_channel_check_h.png
    - images/dk_channel_check_n.png
    - images/dk_channel_expand_h.png
    - images/dk_channel_expand_n.png
    - images/dk_fps_chart.png
    - images/dk_route_arrow.png
    - images/dk_memory_search.png